# Generated by Django 5.0.3 on 2026-05-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
